### ISSUE TITLE
Still mention xvkbd command

### ISSUE THREAD

**Issue by jmdejong** [sasawat/firefox-ctrl-q-workaround#20]
xdotool key does not work properly on all systems.
For me it would not send key combinations properly.
The old code using xvkbd does work for me.

It may be good to mention the xvkbd solution too.
Maybe as outcommented code and a comment explaining that the user should try that if it doesn't work with xdotool

**Comment by sasawat** [comment]
Feel free to do that and I can merge. I'm contractually not allowed to write open source code for the time being.
