### ISSUE TITLE
Woha, this is cool

### ISSUE THREAD

**Issue by MortenGuldager** [sasawat/firefox-ctrl-q-workaround#3]
'Aloha!

Just wanna say your hack works brilliant. Even added an `else` statement to fire a
`notify-send -t 1 "Saved your firefox from a unpleasent CTRL-Q"`

/mogul

**Comment by sasawat** [comment]
Aloha!

Thanks~

**Comment by Xananax** [comment]
Thanks so much for this. Thank you
