### ISSUE TITLE
Noob question - xvkbd usage

### ISSUE THREAD

**Issue by aerosol** [sasawat/firefox-ctrl-q-workaround#4]
Hey is there any good reason for using `xvkbd` over `xdotool` here?

Thanks for this repo BTW, it helped me with some other problem I had.

**Comment by sasawat** [comment]
I tried using `xdotool` wasn't reliably sending ctrl+q in i3wm for some reason. `xvkbd` has worked reliably for me, so I used that instead of trying to get `xdotool` working properly.

**Comment by aerosol** [comment]
Thanks
