### ISSUE TITLE
Doesn't work in Ubuntu Bionic Beaver 

### ISSUE THREAD

**Issue by mcoromac** [sasawat/firefox-ctrl-q-workaround#6]
I don't know if I'm doing it wrong but I downloaded i3-wm package, added the bindsym Ctrl+q exec ~/noctrlq.sh on my i3 config file. And copy the script to /etc/i3/
?

**Comment by sasawat** [comment]
if you bind it to ~/noctrlq.sh then you have to put the script in ~. If you want to put the script elsewhere, you have to change the path.
